### ISSUE TITLE
Can you update the Please dependency version

### ISSUE THREAD

**Issue by rspt** [lmtm/pleeease-loader#1]

**Comment by Delapouite** [comment]
Hi rspt

Thanks for your PR.

Unfortunately the major version number of pleeease can't not be bump without changing the code as well.

https://github.com/iamvdo/pleeease/releases

There's a breaking change in the API which is now async.

Do you mind fixing the code of the loader to take care of this as well? Thanks!

**Comment by rspt** [comment]
Hi Delapouite.

Will do this asap.
